"""Add profile_pic_url to Admin and User models

Revision ID: 93e422029b75
Revises: 
Create Date: 2025-03-06 17:28:09.247618

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93e422029b75'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_pic_url', sa.String(length=255), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_pic', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('profile_pic_url', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('onboarding_completed', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('onboarding_completed')
        batch_op.drop_column('profile_pic_url')
        batch_op.drop_column('profile_pic')

    with op.batch_alter_table('admin', schema=None) as batch_op:
        batch_op.drop_column('profile_pic_url')

    # ### end Alembic commands ###
